[package]
name = "azadi-macros"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
description = "Core macro processing library for Azadi"

[dependencies]
thiserror.workspace = true
serde.workspace = true
serde_json.workspace = true
clap = { version = "4.4", features = ["derive"] }

[dev-dependencies]
tempfile = "3.8"
pretty_assertions = "1.4"
assert_cmd = "2.0"
predicates = "3.0"
escargot = "0.5"

[[bin]]
name = "azadi-macro-cli"
path = "src/bin/macro_cli.rs"
