// crates/azadi-macros/src/evaluator/tests/mod.rs
mod test_case_modifiers;
mod test_def;
mod test_equal;
mod test_eval;
mod test_here;
mod test_if;
mod test_include;
mod test_macro_api;
mod test_macros;
mod test_var;
